### ISSUE TITLE
Parsing images with digest is not clear

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [distribution/reference#11]
Parsing images with digest like `docker.io/library/nginx@sha256:ed6d2c43c8fbcd3eaa44c9dab6d94cb346234476230dc1681227aa72d07181ee` using `Parse` doesn't work without having blank imports for a package that registers hash functions, for example having something like `import _ "crypto/sha256"`.

`go-digest` mention that in their [readme](https://github.com/opencontainers/go-digest?tab=readme-ov-file#usage) as it can lead to some confusion.

IMO, I think it should be mentioned somewhere that you need to have these imports or referencing `go-digest` for example as it is the package where this behavior originates but that's up to you.

playground [link](https://go.dev/play/p/-9uWc4jGrrB).

Thanks!

**Comment by milosgajdos** [comment]
Thanks, yeah this IS annoying. Mind opening a PR for README / godoc?

**Comment by milosgajdos** [comment]
Closing. Addressed by https://github.com/distribution/reference/pull/13
