### ISSUE TITLE
Code coverage not uploading

### ISSUE THREAD

**Issue by Jamstah** [distribution/reference#6]
I assume we need a token for the repo for codecov.io

https://github.com/distribution/reference/actions/runs/6037220875/job/16381063184

**Comment by milosgajdos** [comment]
I dont know how the original repo has been setup - some ancient magic I presume. Maybe it was just linked with Codecov somehow...I need to dig in, but there is no token in GHA settings or secret in the upstream repo

**Comment by Jamstah** [comment]
OK, lmk if there's something I should do (maybe contact codecov?)

**Comment by milosgajdos** [comment]
@Jamstah I have been told that the `codecov` on this repo had to be approved in the org settings which I have no access to. But allegedly it was just approved so I reckon we should push an update and see?

**Comment by Jamstah** [comment]
I just hit re-run.

**Comment by Jamstah** [comment]
Great, working now.

We should probably try and improve the coverage.
